config/routes.rb
Rails.application.routes.draw do
  get 'search/index', as: "search"

  get 'coursesubjects/search', as: "coursesubjects"

  resources :enrollments

  resources :coursesubjects do
    collection do
      get 'search'
      get 'do_search'
    end
  end

  resources :instructors
  resources :subjects
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  get "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  resources :courses

  get "/home" => "home#index", as: "home"

  root 'clearance/sessions#new'

end

app/models/coursesubject.rb
class Coursesubject < ActiveRecord::Base
end

app/controllers/coursesubjects_controller.rb
class CoursesubjectsController < ApplicationController
  before_action :set_coursesubject, only: [:show, :edit, :update, :destroy]
  before_action :require_login
  # GET /coursesubjects
  # GET /coursesubjects.json
  def index
    @coursesubjects = Coursesubject.all
  end

  def search
    #@coursesubjects = Coursesubject.all
    @Coursesubject = Coursesubject.all
    @subjects = Subject.all
    @subjects_name_id = {}
    @coursesubjects = nil
    @subjects.each do |subject|
      @subjects_name_id[subject.name] = subject.id
    end
    @subjects_name_id = Subject.all.map {|s| [s.name, s.subject_id]}
  end

  def do_search
    #binding.pry
    if params.fetch(:course_name) != nil and params.fetch(:course_name) != ""
      if params.fetch(:subject_id) != ""
        @coursesubjects = Coursesubject.where(course_name:params.fetch(:course_name).to_s, subject_id:params.fetch(:subject_id).to_s)
      else
        @coursesubjects = Coursesubject.where(course_name:params.fetch(:course_name))
      end
    end
    respond_to do |format|
      format.js
    end
  end

  # GET /coursesubjects/1
  # GET /coursesubjects/1.json
  def show
  end

  # GET /coursesubjects/new
  def new
    @coursesubject = Coursesubject.new
  end

  # GET /coursesubjects/1/edit
  def edit
  end

  # POST /coursesubjects
  # POST /coursesubjects.json
  def create
    @coursesubject = Coursesubject.new(coursesubject_params)

    respond_to do |format|
      if @coursesubject.save
        format.html { redirect_to @coursesubject, notice: 'Coursesubject was successfully created.' }
        format.json { render :show, status: :created, location: @coursesubject }
      else
        format.html { render :new }
        format.json { render json: @coursesubject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coursesubjects/1
  # PATCH/PUT /coursesubjects/1.json
  def update
    respond_to do |format|
      if @coursesubject.update(coursesubject_params)
        format.html { redirect_to @coursesubject, notice: 'Coursesubject was successfully updated.' }
        format.json { render :show, status: :ok, location: @coursesubject }
      else
        format.html { render :edit }
        format.json { render json: @coursesubject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coursesubjects/1
  # DELETE /coursesubjects/1.json
  def destroy
    @coursesubject.destroy
    respond_to do |format|
      format.html { redirect_to coursesubjects_url, notice: 'Coursesubject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coursesubject
      @coursesubject = Coursesubject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coursesubject_params
      params.require(:coursesubject).permit(:course_code, :course_name, :subject_id)
    end
end

app/helpers/coursesubjects_helper.rb
module CoursesubjectsHelper
end

app/views/coursesubjects/_form.html.erb
<%= form_for(@coursesubject) do |f| %>
  <% if @coursesubject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coursesubject.errors.count, "error") %> prohibited this coursesubject from being saved:</h2>

      <ul>
      <% @coursesubject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_code %><br>
    <%= f.text_field :course_code %>
  </div>
  <div class="field">
    <%= f.label :course_name %><br>
    <%= f.text_field :course_name %>
  </div>
  <div class="field">
    <%= f.label :subject_id %><br>
    <%= f.text_field :subject_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coursesubjects/_index.html.erb
  <table class="table">
    <thead>
      <tr>
        <th>Course code</th>
        <th>Course name</th>
        <th>Subject</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @coursesubjects.each do |coursesubject| %>
        <tr>
          <td><%= coursesubject.course_code %></td>
          <td><%= coursesubject.course_name %></td>
          <td><%= coursesubject.subject_id %></td>
          <td><%= button_to 'Enroll', {:controller => "enrollments", :action => "create", :email=> current_user.email, :course_code => coursesubject.course_code, :course_name=> coursesubject.course_name, :subject_id=> coursesubject.subject_id} , :method=>:post  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/coursesubjects/_search_results.html.erb
<h3>Search Results</h3>

<%if @coursesubjects.nil? || @coursesubjects.length == 0%>
	<p>No Matches Found</p>
<% else %>
	<p><%= @coursesubjects.length %> matches found</p>
	<%= render "index" %>
<% end %>

app/views/coursesubjects/do_search.js.erb
$('#search_results').html("<%= escape_javascript (render(partial: 'search_results')) %>");

app/views/coursesubjects/edit.html.erb
<h1>Editing Coursesubject</h1>

<%= render 'form' %>

<%= link_to 'Show', @coursesubject %> |
<%= link_to 'Back', coursesubjects_path %>

app/views/coursesubjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Coursesubjects</h1>

<table>
  <thead>
    <tr>
      <th>Course code</th>
      <th>Course name</th>
      <th>Subject</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coursesubjects.each do |coursesubject| %>
      <tr>
        <td><%= coursesubject.course_code %></td>
        <td><%= coursesubject.course_name %></td>
        <td><%= coursesubject.subject_id %></td>
        <td><%= link_to 'Show', coursesubject %></td>
        <td><%= link_to 'Edit', edit_coursesubject_path(coursesubject) %></td>
        <td><%= link_to 'Destroy', coursesubject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coursesubject', new_coursesubject_path %>

app/views/coursesubjects/new.html.erb
<h1>New Coursesubject</h1>

<%= render 'form' %>

<%= link_to 'Back', coursesubjects_path %>

app/views/coursesubjects/search.html.erb
<script type="text/javascript" src="http://code.jquery.com/jquery-1.8.2.js"></script>
       <script type="text/javascript">
           function selectOption() {
             var text = document.getElementById("txt").value;
             var select = document.getElementById("slt").value;
             $.get('/coursesubjects/do_search', {course_name: text, subject_id: select});
           }
       </script>

<div class="col-md-offset-1 col-md-4">
<h1>Search Page</h1>
<p>specify both course name and subject to find your course, you can select "Not specified" for subject</p>
<%= form_tag(do_search_coursesubjects_path, method: "get", remote: true, role: "form", class: "form", onchange:"selectOption()") do %>

  <div class="form-group">
    <label class="control-label">Course:</label>
    <%= text_field_tag(:course_name, "", class: "form-control", id: "txt") %>
    <label>Subject:</label>
    <%= select_tag(:subject_id, options_for_select([['Not specified', ""]]+@subjects_name_id), class: "form-control", id: "slt") %>
  </div>

  <!-- <%= submit_tag("Search", class: "btn btn-default" ) %> -->
<% end %>
</div>

<div class="row col-md-offset-1 col-md-11">
  <div id="search_results"></div>
</div>

<!-- <div>
  <form name="query" action="coursesubjects/do_search">
  Course:
  <input type="text" name="course_name">
  Subject:
  <select name="subject_id">
    <option value="">Not specified</option>
    <option value="<%=options_for_select(@subjects_name_id)%>"></option>
  </select><br>
  <input type="submit" value="Search">
  </form>

  <div class="row col-md-offset-1 col-md-11">
    <div id="search_results"></div>
  </div>

</div> -->

app/views/coursesubjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course code:</strong>
  <%= @coursesubject.course_code %>
</p>

<p>
  <strong>Course name:</strong>
  <%= @coursesubject.course_name %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @coursesubject.subject_id %>
</p>

<%= link_to 'Edit', edit_coursesubject_path(@coursesubject) %> |
<%= link_to 'Back', coursesubjects_path %>