config/routes.rb
Rails.application.routes.draw do
  get 'search/index', as: "search"

  get 'coursesubjects/search', as: "coursesubjects"

  resources :enrollments

  resources :coursesubjects do
    collection do
      get 'search'
      get 'do_search'
    end
  end

  resources :instructors
  resources :subjects
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  get "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  resources :courses

  get "/home" => "home#index", as: "home"

  root 'clearance/sessions#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample Rails Bootstrap Application</title>
  <%= stylesheet_link_tag "application", media: "all",
                          "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header" class="btn-group">
    <% if signed_in? -%>
      <%= link_to t(".sign out"), sign_out_path, class: "btn btn-default"%>
      <%= link_to t(".home page"), home_path, class: "btn btn-default"%>
      <%= link_to t(".search page"), coursesubjects_path, class: "btn btn-default"%>
      <%= link_to t(".courses"), courses_path, class: "btn btn-default"%>
      <%= link_to t(".subjects"), subjects_path, class: "btn btn-default"%>
      <%= link_to t(".instructors"), instructors_path, class: "btn btn-default"%>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path, class: "btn btn-default" %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>